version: '2'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - clientes
            - carrito
            - productos
            - cantidad
            - apicrud
            - apimid
        ports:
            - "8080:80"
        
    clientes:
        build: ./clientes

    productos:
        build: ./productos

    carrito:
        build: ./carrito
    
    cantidad:
        build: ./cantidad    

    apicrud:
        build: ./apicrud
    
    apimid:
        build: ./apimid