version: '2'
services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - clientes
            - productos
            - resta
            - apicrud
        ports:
            - "8080:80"
        
    clientes:
        build: ./clientes

    productos:
        build: ./productos

    resta:
        build: ./resta

    apicrud:
        build: ./apicrud